### ISSUE TITLE
Decoder fails after certain number of packets received

### ISSUE THREAD

**Issue by fmiceli24** [catid/siamese#2]
Hi Chris,

I have a few questions about the use of a return channel for siamese acks.

- Is it mandatory to use the `siamese_decoder_ack()` `siamese_encoder_ack()` functions?
- Instead of those, can I just send the last received packet number and use the `SiameseResult siamese_encoder_remove_before()` function?
- If I do the latter what would I be missing?

Thanks!

**Comment by catid** [comment]
I think that would cause the encoder to stop sending data the decoder is
missing so the decoder would get stuck.

**Comment by fmiceli24** [comment]
I understand. But if I send the last packet number received **in order**, then it would work. right?

I say this because on the streaming unit test `siamese_encoder_remove_before()` is the function you use to simulate the ack. And there you use the next expected packet number in order.

**Comment by fmiceli24** [comment]
Up to a point this works. But then it does not let me keep adding recovery packets to the decoder. Will end up sending the ack's.

Thanks.

**Comment by fmiceli24** [comment]
I renamed the issue to reflect what I am facing now.

- I am sending 1 recovery every 3 originals
- I am using as feedback just the `siamese_encoder_remove_before()` using nextExpectedPacketNum. This part is not shown in the code below.
- I am receiving in order thanks to the `siamese_decoder_get` function.

The problem I am facing is that after a few packets are received (around 17000) the `siamese_decoder_add_original` and `siamese_encoder_add_recovery` functions start to fail with error code 5.

Is my problem the feedback not being with the ack's or just me not interpreting correctly the API?

Thanks!

This is my sender function (error handling omitted so as to paste less code):

```cpp
//Original data within packet
siameseResult = siamese_encoder_add(encoder, &original);
writeB[FEC_TYPE_IDX] = 0x0;  //original
memcpy(&writeB[PACKET_N_IDX], &original.PacketNum, sizeInt);
_socket.send_to(boost::asio::buffer(writeB, original.DataBytes + HEADER), remoteEndpoint);
TimeToSendRecoveryPacket = (original.PacketNum % kRecoveryRate == 0) && (original.PacketNum != 0);
if (TimeToSendRecoveryPacket)
{
    writeB[FEC_TYPE_IDX] = 0x1; //recovery
    siameseResult = siamese_encode(encoder, &recovery);
    if (siameseResult != Siamese_NeedMoreData)
        memcpy(&writeB[PACKET_N_IDX], recovery.Data, recovery.DataBytes);
	_socket.send_to(boost::asio::buffer(writeB, recovery.DataBytes + HEADER), remoteEndpoint);
    }				
}
```

And this is my receiver function:
```cpp
if ((readBuffer[FEC_TYPE_IDX] & 0x1) == 0x0){ //Original
    original.Data = &readBuffer[NALU_SIZE_IDX];
    original.DataBytes = bytes_recibidos - HEADER; 
    original.PacketNum = (readBuffer[PACKET_N_IDX + 3] << 24) |
			(readBuffer[PACKET_N_IDX + 2] << 16) |
			(readBuffer[PACKET_N_IDX + 1] << 8) |
			(readBuffer[PACKET_N_IDX]);
    siameseResult = siamese_decoder_add_original(decoder, &buffer);
} else {
    SiameseRecoveryPacket recovery;
    recovery.Data = &readBuffer[PACKET_N_IDX]; //Recovery packets have its payload after the FecTypeIdx
    recovery.DataBytes = bytes_recibidos - PACKET_N_IDX;
    siameseResult = siamese_decoder_add_recovery(decoder, &recovery);
}

while (siamese_decoder_is_ready(decoder) != SiameseResult::Siamese_NeedMoreData)
{
    SiameseOriginalPacket *decodedArray;
    unsigned int count = 0;
    siameseResult = siamese_decode(decoder, &decodedArray, &count);
        if (siameseResult == SiameseResult::Siamese_Success)
	{
	    LOG(DEBUG) << count << " packets recovered";
	}
	else {
	    LOG(DEBUG) << "Error while recovering packets: " << siameseResult;
	}
}

for (;;)
{
    SiameseOriginalPacket original;
    original.PacketNum = nextExpectedPacketNum;
    siameseResult = siamese_decoder_get(decoder, &original);
    if (siameseResult == Siamese_Success)
    {
        nextExpectedPacketNum++;
	FECTol = FEC_TOL_DEFAULT;//3
        LOG(DEBUG) << "Original packet " << original.PacketNum << " decoded";
	continue;
    }
    else {
        if (0 == FECTol--){//Find closest recoverable packet in order not to block
            original.PacketNum++;
	    while (siamese_decoder_get(decoder, &original) != SiameseResult::Siamese_Success){
	        original.PacketNum++;
	    }
	    nextExpectedPacketNum = original.PacketNum + 1;
	    FECTol = FEC_TOL_DEFAULT;
	    LOG(DEBUG) << "Skipped to packet " << original.PacetNum;
        }
    }
    break;
}
```

**Comment by fmiceli24** [comment]
I figured it out. The problem was that the recovery packets were being truncated and so the decoder failed.

But if you could clarify to me what effect the usage of `siamese_encoder_remove_before()` instead of the ack's would have on the FEC process it would be very helpful.

Thanks.

**Comment by catid** [comment]
Do you have a minimal test case?  Nbd if not I can look into it

**Comment by fmiceli24** [comment]
Don't mind looking into the code. As I mentioned It was an error on my side (truncating recovery packets).

I just wanted to know how using `siamese_encoder_remove_before` instead of the ack functions would negatively impact the FEC.

Thanks again.

**Comment by catid** [comment]
Oh I see it was resolved but you would like clarification on the two APIs:

siamese_encoder_remove_before() calls Encoder::RemoveBefore()
This code path calls EncoderPacketWindow::RemoveBefore() to clear up buffer space, but it does not call UpdateRTO() to update the retransmit timeout.

siamese_encoder_ack() calls Encoder::Acknowledge() which invokes EncoderAcknowledgementState::OnAcknowledgementData().
This code path calls EncoderPacketWindow::RemoveBefore() to clear up buffer space, and also UpdateRTO() to update the retransmit timeout.

This means that the main difference between the two is that you don't get an accurate RTO for the roll-up version.

**Comment by catid** [comment]
So the siamese_encoder_retransmit() aka Encoder::Retransmit() function does not have an accurate RTO to work off of if you use only siamese_encoder_remove_before()

**Comment by catid** [comment]
You could try adding UpdateRTO() to the Encoder::RemoveBefore() for your use case?

**Comment by catid** [comment]
You'd want to do it *after* TheWindow->RemoveBefore() inside Encoder::RemoveBefore()

**Comment by catid** [comment]
If the RTO looks like it's updating and giving you valid results after that patch then you're probably good to go

**Comment by fmiceli24** [comment]
Great. Thanks for the explanation.

I will probably implement the ack's on my backchannel in order to fully comply with your implementation. 

Thanks again.

Best,
