### ISSUE TITLE
How often to ack for latency sensitive software

### ISSUE THREAD

**Issue by fmiceli24** [catid/siamese#3]
Hi Chris,

Mi application, if you remember, is a latency sensitive one.

So a couple of questions about the ack's and the retransmission time for this type of software.
- How often should I send the ack's in order not to load the network but to be able to recover using retransmitted packets (within reasonable time ~ 10-12 ms)?
- Retransmission should be checked right after the ack has been submitted to the encoder, right?

**Comment by catid** [comment]
I'd recommend experimenting with different act intervals to see what works
best for you.  Ideally the erasure code will fill in before the acks are
used almost all the time.

**Comment by catid** [comment]
Retransmission should be checked after yeah

**Comment by fmiceli24** [comment]
Chris, Just another question.

Is the decoder and its functions thread safe? Can I call siamese_decoder_add() from one thread while also calling siamese_decoder_get() from another thread without a lock?

Thanks

**Comment by catid** [comment]
I'm pretty sure it is not thread-safe so you'd need the lock

**Comment by fmiceli24** [comment]
OK. Thanks for taking the time to answer. 

Closing this.

**Comment by fmiceli24** [comment]
Hi Chris,

I am evaluating not having retransmissions on the channel because of the real-time nature of my data flow. 

Since I have an upper layer that orders the packets for me, I am evaluating not using the decoder's ack nor the encoder retransmissions. Just the FEC recovery.

In order to do that I am considering periodically resetting the encoder with the  siamese_encoder_remove_before() function in order not to go over the encoder packet count limit.

Is this something supported? Will the FEC recovery work even if I am artificially doing the ack?

Thanks again!
