### ISSUE TITLE
Crash on siamese_decoder_is_ready(...)

### ISSUE THREAD

**Issue by fmiceli24** [catid/siamese#5]
Hi Chris,

We have found a crash that started happening on a Windows 10 Pro Workstation after a chipset driver update.

It throws an illegal instruction crash whenever siamese_decoder_is_ready gets called.

UnitTest also fails with exit code: -1073741795

Do you know of any build time options we could tweak in order not to get such error?

I am attaching the CPU-z for that machine.

[DESKTOP-VN3QP7U.txt](https://github.com/catid/siamese/files/7913831/DESKTOP-VN3QP7U.txt)

**Comment by catid** [comment]
Hm probably some of the SSE instructions are not supported on that processor for some reason

**Comment by fmiceli24** [comment]
Thanks Chris.

Yes. I think the same. The processor is reporting that it supports
something that it does not.

You can close this issue. It is an extra weird case.

Best,
